title: Júlio Zampietro
#logo:
description: A historian by training, I'm currently leveraging my analytical skills to navigate the dynamic world of data analysis and data science.
show_downloads: true
theme: jekyll-theme-minimal
